### ISSUE TITLE
About accelerate or decelerate in `ModelExample.py`

### ISSUE THREAD

**Issue by maple-zhou** [PJLab-ADG/LimSim#5]
It seems that the code doesn't address accelerate or decelerate?
I have read the source code, and all the functions concerning trajectories do not take accelerate or decelerate into control.
Is this temporary and will be updated in the future?

Or am I wrong? Is there something I haven't noticed?

**Comment by Fdarco** [comment]
Thank you for using LimSim. I understand that you want to control the behavior of the vehicle by inputting acceleration and deceleration. However, LimSim controls the movement of the vehicle through trajectories. The definition of trajectories can be found in `./utils/trajectory.py`, in the `Trajectory` and `State` classes. Our `Trajectory` is composed of a series of `State`s, each of which includes information about the vehicle’s position, speed, yaw, and acceleration. In ModelExample.py, we use the function `model.setTrajectories()` to plan future trajectories for the vehicle. The input to this function is a dictionary where the keys are the vehicle `id`s and the values are the planned trajectories.

**Comment by maple-zhou** [comment]
Thanks for your response, I've got what you meant.
Then there is another question:
In `./trafficManager/common/vehicle.py`, the class `Behaviour` contains some elements, including
    KL = 0
    AC = 1
    DC = 2
    LCL = 3
    LCR = 4
    STOP = 5
    IN_JUNCTION = 6
    OVERTAKE = 7
    OTHER = 100
I only found behaviours 'KL', 'LCL', 'LCR', 'STOP', 'IN_JUNCTION' are processed, it seems that the codes do not process 'AC', 'DC' (I guess they refer to 'accelerate' and 'decelerate' respectively), so is it now meaningless in the code?

**Comment by Fdarco** [comment]
Thank you for your in-depth use of the LimSim code. In the `trafficManager` module of LimSim, we plan the trajectory for vehicles through the prediction-decision-planning steps. The behavior generated by the decision process is passed to the planning module to generate the trajectory. As you mentioned, our `AC` and `DC` behaviors are not explicitly handled, this is because the planning module automatically determines the vehicle’s speed and acceleration. Therefore, `AC`, `DC`, and `KL` are the same for our planning module, but the vehicle can still make acceleration and deceleration actions.

Of course, users can write their planning modules to replace our planning module, so that each behavior can take effect. We reserve these behaviors so that users can more easily customize the planning module without having to consider the upstream decision module, making it easier for users to use. 😊

**Comment by maple-zhou** [comment]
Thanks for your quick response!
So if I want to use my own `decision_maker`, it seems it's enough to only transfer desicion.action consisting of 'LCL' and 'LCR'?

**Comment by Fdarco** [comment]
In fact, if you just want to write a decision_maker for the ego, you can take a look at the `EgoPlanner.plan()` function in `./trafficManager/planner/ego_vehicle_planner.py`. In this function, our planning module can handle 5 behaviors including `KL`, `STOP`, `LCR`, `LCL`, and `IN_JUNCTION`. 

Similarly, if you want to make multi-vehicle decisions, you can refer to the `MultiVehiclePlanner.generate_trajectory()` function in `./trafficManager/planner/multi_vehicle_planner.py`, which also supports multiple behaviors. 😊

**Comment by maple-zhou** [comment]
Ohh I've got the logic of the code. Thanks very much of your active response!!!

**Comment by Fdarco** [comment]
After receiving the upstream behavior, our planner module also has a safety check. We don’t just plan a `keep lane` trajectory based on the `KL` instruction, but first determine whether the vehicle needs to stop. That is to say, when the vehicle speed is lower than `10/3.6`, we will first determine whether the vehicle needs to stop. If it needs to stop, we will generate a `STOP` trajectory, otherwise, we will continue to generate a `KL` trajectory.

If you want the planner module to faithfully execute the upstream behavior instructions, you may need to modify the code to remove the safety check part of the planner module. 

In addition, thank you for your in-depth understanding of LimSim’s code. If you are interested, you can join our WeChat group chat to discuss together. 😊

![微信图片_20230809190540](https://github.com/PJLab-ADG/LimSim/assets/26219929/82fbaf02-3ac3-42fc-b729-ebb5ff09cae9)

**Comment by maple-zhou** [comment]
Thanks a lot for your detailed explanation! I have joined the WeChat group.

**Comment by xuarehere** [comment]
> After receiving the upstream behavior, our planner module also has a safety check. We don’t just plan a `keep lane` trajectory based on the `KL` instruction, but first determine whether the vehicle needs to stop. That is to say, when the vehicle speed is lower than `10/3.6`, we will first determine whether the vehicle needs to stop. If it needs to stop, we will generate a `STOP` trajectory, otherwise, we will continue to generate a `KL` trajectory.
> 
> If you want the planner module to faithfully execute the upstream behavior instructions, you may need to modify the code to remove the safety check part of the planner module.
> 
> In addition, thank you for your in-depth understanding of LimSim’s code. If you are interested, you can join our WeChat group chat to discuss together. 😊
> 
> ![微信图片_20230809190540](https://private-user-images.githubusercontent.com/26219929/259589807-82fbaf02-3ac3-42fc-b729-ebb5ff09cae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTQzOTksIm5iZiI6MTcxNjc5NDA5OSwicGF0aCI6Ii8yNjIxOTkyOS8yNTk1ODk4MDctODJmYmFmMDItM2FjMy00MmZjLWI3MjktZWJiNWZmMDljYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjFkMjY1ZTI0M2UxOGJiYWViMjQ4NGUyYWZhNTgwNjRlYzBjNmRmYjFmOTYzYzg4NzhkMDc3YmMzNmQ3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhZKxitlfVUy4Bb-SRaDa4zS--JCegT564T67UEhTwA)

The QR code is invalid. Can you resend it?

**Comment by Fdarco** [comment]
> > After receiving the upstream behavior, our planner module also has a safety check. We don’t just plan a `keep lane` trajectory based on the `KL` instruction, but first determine whether the vehicle needs to stop. That is to say, when the vehicle speed is lower than `10/3.6`, we will first determine whether the vehicle needs to stop. If it needs to stop, we will generate a `STOP` trajectory, otherwise, we will continue to generate a `KL` trajectory.
> > If you want the planner module to faithfully execute the upstream behavior instructions, you may need to modify the code to remove the safety check part of the planner module.
> > In addition, thank you for your in-depth understanding of LimSim’s code. If you are interested, you can join our WeChat group chat to discuss together. 😊
> > ![微信图片_20230809190540](https://private-user-images.githubusercontent.com/26219929/259589807-82fbaf02-3ac3-42fc-b729-ebb5ff09cae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTQzOTksIm5iZiI6MTcxNjc5NDA5OSwicGF0aCI6Ii8yNjIxOTkyOS8yNTk1ODk4MDctODJmYmFmMDItM2FjMy00MmZjLWI3MjktZWJiNWZmMDljYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjFkMjY1ZTI0M2UxOGJiYWViMjQ4NGUyYWZhNTgwNjRlYzBjNmRmYjFmOTYzYzg4NzhkMDc3YmMzNmQ3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhZKxitlfVUy4Bb-SRaDa4zS--JCegT564T67UEhTwA)
> 
> The QR code is invalid. Can you resend it?

![204551575a73f9171f7cd49b1fec4e4](https://github.com/PJLab-ADG/LimSim/assets/26219929/83e06704-6e98-44b0-94f9-162b6dbd8b80)
